FORMAT: 1A
HOST: http://lambda.dunamulab.com/api/v1

# Lambda Token Backend API

Lambda is APIs allowing services to perfom actions on chains

## Authentication [/auth?{api_key,api_secret}]

### Get Authentication Code [GET]

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "token": "Bearer TOKEN",
                "published_at": "2018-07-05T08:40:51.620Z",
                "refresh_token": "REFRESH_TOKEN"
            }

## Users [/users]

### Create a New User [POST]

You may create a user using this action. It takes a JSON
object containing required data.

+ Request (application/json)

    + Headers

            Authorization: Bearer {auth_token}

    + Body

            {
                "first_name": "Yoshi",
                "last_name": "Munchakoopas",
                "additional_data": {

                }
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "success": true
            }

+ Response 400 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "success": false,
                "error": {
                  "description": "Required fields are missing",
                  "additional_data": {

                  }
                }
            }

+ Response 401 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "success": false,
                "error": {
                  "description": "Authorization required",
                  "additional_data": {

                  }
                }
            }

+ Response 403 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "success": false,
                "error": {
                  "description": "Permission denied",
                  "additional_data": {

                  }
                }
            }

+ Response 500 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "success": false,
                "error": {
                  "description": "Something went wrong - please try again later",
                  "additional_data": {

                  }
                }
            }
